# Configuración básica de Gradle
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
# No tratar warnings como errores
# org.gradle.warning.mode=none

# Android
android.useAndroidX=true
android.enableJetifier=false

# Kotlin
kotlin.incremental=true
kotlin.caching.enabled=true
# Suprimir warnings de deprecated (no recomendado a largo plazo)
# kotlin.warning.deprecated.usage=false

# KSP
ksp.incremental=true

# Forzar uso de JDK 17
org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.20.101

# Proxy HTTP
# systemProp.http.proxyHost=proxy.jcyl.es
# systemProp.http.proxyPort=80
# systemProp.http.proxyUser=garlanja
# systemProp.http.proxyPassword=Almanz0r0198357
# systemProp.http.nonProxyHosts=localhost|127.0.0.1

# Proxy HTTPS
# systemProp.https.proxyHost=proxy.jcyl.es
# systemProp.https.proxyPort=80
# systemProp.https.proxyUser=garlanja
# systemProp.https.proxyPassword=Almanz0r0198357
