org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.disallowKotlinSourceSets=false

# Forzar uso de JDK 17
org.gradle.java.home=C:\\Program Files\\Microsoft\\jdk-17.0.20.101

# Deshabilitar caché incremental de KSP
ksp.incremental=false
ksp.incremental.log=true
ksp.allow.all.target.configuration=false

# Deshabilitar caché problemática
org.gradle.caching=false
org.gradle.configuration-cache=false

# Proxy HTTP
systemProp.http.proxyHost=proxy.jcyl.es
systemProp.http.proxyPort=80
systemProp.http.proxyUser=garlanja
systemProp.http.proxyPassword=Almanz0r0198357
systemProp.http.nonProxyHosts=localhost|127.0.0.1

# Proxy HTTPS
systemProp.https.proxyHost=proxy.jcyl.es
systemProp.https.proxyPort=80
systemProp.https.proxyUser=garlanja
systemProp.https.proxyPassword=Almanz0r0198357
